version: "3"
services:
  summarizer:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - ollama
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11435"
    volumes:
      - ${HOME}/.ollama:/root/.ollama