version: "3"
services:
  summarizer:
    build: .
    ports:
      - 8501:8501
    depends_on:
      - ollama
    env_file:
      - .env
  ollama:
    image: ollama/ollama:latest
    env_file:
      - .env
    volumes:
      - ./.ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
