version: "3"
services:
  summarizer:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - ollama
    env_file:
      - .env
  ollama:
    image: ollama/ollama:latest
    env_file:
      - .env
    volumes:
      - ./.ollama:/root/.ollama
